version: 2

models:
  - name: int_localbike__order_items
    description: "Enhanced sales details with net/gross revenue calculations and product information."
    columns:
      - name: order_id
        tests:
          - not_null
      - name: item_id
        tests:
          - not_null
      - name: net_amount
        description: "Income after discount."
        tests:
          - not_null

  - name: int_localbike__orders
    description: "Orders enhanced with store information and status details."
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "order_status IN (1, 2, 3, 4)"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: order_status

  - name: int_localbike__stock_performance
    description: "Analysis of inventory availability and value of fixed capital."
    columns:
      - name: product_id
        tests:
          - not_null
      - name: stock_quantity
        tests:
          - not_null
      - name: inventory_status
        tests:
          - accepted_values:
              arguments:
                values:
                  - OUT OF STOCK
                  - CRITICAL STOCK
                  - LOW STOCK
                  - ENOUGH STOCK