version: 2

sources:
  - name: analytics4
    schema: analytics4
    tables:
      - name: events_20210131
      
  - name: google_sheets
    schema: google_sheets
    tables:
      - name: responsables_territoires

  - name: sales_database
    schema: sales_database
    tables:
      - name: feedback
      - name: payment
      - name: product
      - name: order
      - name: order_item
      - name: seller
      - name: user
      
  - name: airbnb
    schema: airbnb
    tables:
      - name: listings
   
  - name: localbike
    schema: localbike
    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores